[serviceweaver]
binary = "./onlineboutique"
rollout = "5m"

[gke]
regions = ["us-west1"]
public_listener = [
  {name = "boutique", hostname = "onlineboutique.example.com"},
]

["github.com/weaver/examples/onlineboutique/cartservice/CartCache"]
cache_host = "localhost:6379"
cache_ttl = "3m"